# kickstart travis.
language: java

before_install:
 - git clone https://github.com/ivanceras/parent.git
 - pwd
 - ls
 - echo `pwd`
 - cd parent
 - mvn clean install -Dgpg.skip=true

install: 
 - mvn install -Dgpg.skip=true
